\documentclass{article}
\begin{document}

This is all you need to do if you want to go back to the Sweave style:

<<setup, include=FALSE>>=
render_sweave()
@

The quick brown fox jumps over the lazy dog the quick brown fox jumps over the
lazy dog the quick brown fox jumps over the lazy dog.

<<test>>=
1+1
rnorm(30)
@

The quick brown fox jumps over the lazy dog the quick brown fox jumps over the
lazy dog the quick brown fox jumps over the lazy dog.

\end{document}
