\documentclass{beamer}

\title{Test framebreaks}
\author{Yihui Xie}
\begin{document}

\maketitle
<<setup, include=FALSE>>=
# the kframe environment does not work with allowframebreaks, so remove it
knit_hooks$set(document = function(x) {
  gsub('\\\\(begin|end)\\{kframe\\}', '', x)
})
@

\begin{frame}[allowframebreaks,fragile]
\frametitle{Preliminaries}
<<step0,size="footnotesize">>=
example(step)
@
\end{frame}

\end{document}
