#!/bin/bash

prefix=${1%.*}-
Rscript -e "library(knitr); opts_knit\$set(base.url='http://animation.r-forge.r-project.org/knitr-ex/'); opts_chunk\$set(cache.path='cache/$prefix', fig.path='figure/$prefix'); set.seed(123); knit('$1')"
