#!/bin/bash

ls | grep -E '^[0-9].*\.(brew|R(nw|md|tex|html|rst|asciidoc|textile))$' | grep -E -v '^(076|078)-' | xargs -n1 -P4 ./k > /dev/null
Rscript -e "knitr::purl('094-purl.Rmd')"
./k "076-chinese-gb2312.rnw', '076-chinese-gb2312.TEX', encoding='GB2312"
./k "078-chinese-big5.rnw', '078-chinese-big5.ctx', encoding='BIG5"
# Explicitly run caching test twice
./k "101-cache-levels.Rmd"
# load_cache() requires running twice
./k "114-load-cache.Rmd"
