#!/bin/bash

for i in `ls | grep -E '^[0-9].*\.R(nw|md|tex|html|rst)$'`
do
  prefix=${i%.*}-
  Rscript -e "library(knitr); opts_chunk\$set(cache.path='cache/$prefix', fig.path='figure/$prefix'); set.seed(123); knit('$i')"
done

